version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.17.8
    environment:
      - http.cors.enabled=true
      - http.cors.allow-origin=/.*/
      - node.name=elasticsearch-node
      - cluster.name=elasticsearch-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - webnet
  elasticvue:
    image: cars10/elasticvue
    ports:
      - 8080:8080
    networks:
      - webnet
  sql-server-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=SuperStr0ng
      - ACCEPT_EULA="Y"
    networks:
      - webnet
volumes:
  elasticsearch-data:
networks:
  webnet:
    driver: bridge
