version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.17.8
    environment:
      - node.name=elasticsearch-node
      - cluster.name=elasticsearch-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
  keycloak:
    image: jboss/keycloak:11.0.2
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=password
    ports:
      - 8080:8080
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 3000:3000
volumes:
  elasticsearch-data:
